config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "/", to: "homepage#home", as: "root"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :articles
  resources :projects
  resources :contacts, only: [:new, :create]

  get '*path' => redirect('/')
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name, :validate => true
  attribute :email, :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message, :validate => true
  attribute :nickname, :captcha => true

  def headers
    {
    :subject => "Contact Form",
    :to => "jpdwalker@gmail.com",
    :from => %("#{name}" <#{email}>)
  }
  end
end

app/models/project.rb
class Project < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @articles = Article.all.order("created_at desc").paginate(page: params[:page], per_page: 5)
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article, notice: "Saved"
    else
      render 'new', notice: "Unsuccesful save"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update article_params
      redirect_to @article, notice: "Article saved"
    else
      render 'edit'
    end
  end

  def destroy
    @article.destroy

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :content, :slug)
  end

  def find_article
    @article = Article.friendly.find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    @contact.request = request
    if @contact.deliver
      flash.now[:error] = nil
    else
      flash.now[:error] = 'Cannot send message.'
      render :new
    end
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def home
    @articles = Article.all.limit(3).order("created_at desc")
    @projects = Project.all.limit(3).order("created_at desc")
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def contact
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :find_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @projects = Project.all.order("created_at desc")
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project, notice: 'Project saved'
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Updated'
    else
      render 'edit'
    end
  end

  def destroy
    @project.destroy

    redirect_to projects_path
  end

  private


  def find_project
    @project = Project.friendly.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:title, :description, :link, :slug)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  class HTMLwithPygments < Redcarpet::Render::HTML
    def block_code(code, language)
      Pygments.highlight(code, lexer: language)
    end
  end

  def markdown(content)
    renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
    options = {
      autolink: true,
      no_intra_emphasis: true,
      disable_indented_code_blocks: true,
      fenced_code_blocks: true,
      lax_html_blocks: true,
      strikethrough: true,
      superscript: true,
    }
    Redcarpet::Markdown.new(renderer, options).render(content).html_safe
  end
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/articles/_disqus.html.erb
<div id="disqus_thread"></div>
<script>

/**
*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/

// var disqus_config = function () {
// this.page.url = '<%= url_for([@article]) %>';  // Replace PAGE_URL with your page's canonical URL variable
// this.page.identifier = '<%= @article.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
// };

    (function() { // DON'T EDIT BELOW THIS LINE
    var d = document, s = d.createElement('script');
    s.src = 'https://joewalker.disqus.com/embed.js';
    s.setAttribute('data-timestamp', +new Date());
    (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>

app/views/articles/_form.html.erb
<%= form_for @article do |f| %>
  <% if @article.errors.any? %>
  <h2><%= pluralize(@article.errors.count, "error") %> prevented this article from saving:</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :content, "Write your article here" %><br>
  <%= f.text_area :content, input_html: {style: 'height:200px'}  %>

  <br>
  <br>

  <%= f.submit %>


<% end %>

app/views/articles/edit.html.erb
<h1 id="page-title">Edit Article</h1>
<div class="skinny-wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<h1 id="page-title">Writings</h1>
<div id="posts-wrapper" class="skinny-wrapper">
  <% @articles.each do |article| %>
    <div class="post">
      <p class="date"><%= article.created_at.strftime('%B %d, %Y') %></p>
      <h2><%= link_to article.title, article %></h2>
      <hr>
    </div>
  <% end %>

</div>

 <%= will_paginate @articles %>

app/views/articles/new.html.erb
<h1 id="page-title">New Article</h1>
<div class="skinny-wrapper wrapper_padding">
  <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div id="post_show_content" class="skinny-wrapper wrapper_padding">
  <header>
    <p class="date"><%=  @article.created_at.strftime("%b %d, %Y" ) %></p>
    <h1><%= @article.title %></h1>
    <hr>
  </header>

  <div id="content">
    <p><%= markdown @article.content %></p>
  </div>

  <% if user_signed_in? %>
    <div id="admin_links">
      <%= link_to "Edit Article", edit_article_path(@article)  %>
      <%= link_to "Delete Article", article_path(@article), method: :delete, data: { confirm: "Are you sure?"}  %>
    </div>
  <% end %>

  <hr>

  <div id="share_box">
    <p>Share <%= @article.title %></p>
    <!-- Twitter -->
    <a onClick="javascript:window.open('http://twitter.com/share?text=<%= @article.title %> &amp;url=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fab fa-twitter"></i></a>
    <!-- Facebook -->
     <a onClick="javascript:window.open('http://facebook.com/sharer.php?u=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fab fa-facebook"></i></a>
    <!-- LinkedIn -->
     <a onClick="javascript:window.open('http://plus.google.com/share?url=<%= url_for([@article, {only_path: false}]) %>', '_blank', 'width=800, height=500, top=200, left=300');void(0);"><i class="fab fa-linkedin"></i></a>
  </div>

  <hr>

  <%= render 'disqus' %>

</div>

app/views/contacts/create.html.erb
<h1 id="page-title">Get in touch!</h1>
<div class="skinny-wrapper wrapper_padding">
  <h1>Thank you for your message!</h1>
  <p>I will get back to you soon.</p>
</div>

app/views/contacts/new.html.erb
<h1 id="page-title">Get in touch!</h1>
<div class="skinny-wrapper wrapper_padding">
  <%= form_for @contact do |f| %>
  <%= f.label :name %> <br>
  <%= f.text_field :name, required: true %>

  <br>

  <%= f.label :email %> <br>
  <%= f.email_field :email, required: true %>

  <br>

  <%= f.label :message %> <br>
  <%= f.text_area :message, as: :text %>

  <div class="hidden">
    <%= f.label :nickname %> <br>
    <%= f.text_field :nickname, hint: 'leave this field blank' %>
  </div>

    <%= f.submit 'Send message', class: "button" %>
  <% end %>
</div>

app/views/homepage/home.html.erb
<div class="viewpoint">
  <header class="header">
  <%= render 'shared/header' %>


  <div class="wrapper wrapper_padding clearfix">
    <div class="col-1 about homepage_content">
      <h2>About</h2>
      <hr>
      <p>I'm Joe, a Full Stack Developer from London, UK.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Pariatur, vitae.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam id officia ex, iusto voluptate ad commodi a veniam, rerum eveniet?</p>
    </div>
    <div class="col-2 homepage_content">
      <h2>Writings</h2>
      <hr>
      <% @articles.each do |article| %>
        <h3><a href=""><%= link_to article.title, article %></a></h3>
        <p class="date"><%= article.created_at.strftime("%b %d, %Y" ) %></p>
      <% end %>

    </div>
    <div class="col-3 homepage_content">
      <h2>Projects</h2>
      <hr>
      <% @projects.each do |project| %>
        <h3><a href=""><%= link_to project.title, project %></a></h3>
        <p class="date"><%= project.created_at.strftime("%b %d, %Y" ) %></p>
      <% end %>

    </div>
  </div>
   </header>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Joe Walker - Full Stack Developer</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="//kit.fontawesome.com/54975fbe75.js"></script>
    <link href="//fonts.googleapis.com/css?family=DM+Sans&display=swap" rel="stylesheet">
    <link rel='icon' type='image/png' href='favicon.png' />
  </head>


  <body>

  <% if notice %>
    <p class="notice"><%= notice %></p>
  <% elsif alert %>
    <p class="alert"><%= alert %></p>
  <% end %>

    <%= yield %>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/contact.html.erb
  <h1 id="page-title">Get in touch!</h1>

  <div class="skinny-wrapper wrapper-padding">
  <label>Name</label><br>
  <input type="text">

  <br>

  <label>Email</label><br>
  <input type="text">

  <br>

  <label>Message</label><br>
  <textarea></textarea>

  <br>

  <input type="submit" value="Send Message" class="button">
  </div>

  <br>

app/views/projects/_form.html.erb
<%= form_for @project do |f| %>
  <% if @project.errors.any? %>
  <h2><%= pluralize(@project.errors.count, "error") %> prevented this project from saving:</h2>
  <ul>
    <% @project.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>

  <%= f.label :title %><br>
  <%= f.text_field :title %>

  <br>
  <br>

  <%= f.label :description %><br>
  <%= f.text_area :description %>

  <br>
  <br>


  <%= f.label :link %><br>
  <%= f.text_field :link %>


  <%= f.submit %>


<% end %>

app/views/projects/edit.html.erb
<h1 id="page-title">Edit Project</h1>
<div class="skinny-wrapper wrapper-padding">
  <%= render 'form' %>
</div>

app/views/projects/index.html.erb
<h1 id="page-title">Projects</h1>
<div id="posts-wrapper" class="skinny-wrapper">
  <% @projects.each do |project| %>
    <div class="post">
      <p class="date"><%= project.created_at.strftime('%B %d, %Y') %></p>
      <h2><%= link_to project.title, project %></h2>
      <hr>
    </div>
  <% end %>

</div>

 <%#= will_paginate @articles %>

app/views/projects/new.html.erb
<h1 id="page-title">New Project</h1>
<div class="skinny-wrapper wrapper-padding">
  <%= render 'form' %>
</div>

app/views/projects/show.html.erb
<div id="post_show_content" class="skinny-wrapper wrapper_padding">
  <header>
    <p class="date"><%=  @project.created_at.strftime("%b %d, %Y" ) %></p>
    <h1><%= @project.title %></h1>
    <hr>
  </header>

  <div id="content">
    <p><%= markdown @project.description %></p>
    <div class="button_wrapper">
      <a href="<%= @project.link %>" class="project_button" target="_blank">Visit <%= @project.title %></a>
    </div>
  </div>

    <% if user_signed_in? %>
    <div id="admin_links">
      <%= link_to "Edit Project", edit_project_path(@project)  %>
      <%= link_to "Delete Project", project_path(@project), method: :delete, data: { confirm: "Are you sure?"}  %>
    </div>
  <% end %>

  <hr>

</div>

app/views/shared/_footer.html.erb
  <footer id="main_footer">
    <p class="copyright">&copy; 2019 Joe Walker</p>
    <nav>
      <a href="https://www.linkedin.com/in/joe-walker-4a353b101/" target="_blank"><i class="fab fa-linkedin"></i></a>
      <a href="https://github.com/jpdwalker" target="_blank"><i class="fab fa-github-square"></i></a>
      <a href="https://www.facebook.com/joe.walker.543" target="_blank"><i class="fab fa-facebook-square"></i></a>
    </nav>

  </footer>

app/views/shared/_header.html.erb
  <header id="main-navigation" class="clearfix">
    <%= link_to 'Joe Walker', root_path, :class => 'name' %>
    <nav>
      <%= link_to "Articles", articles_path  %>
      <%= link_to "Projects", projects_path  %>
       <%= link_to 'Contact', new_contact_path  %>
      <% if user_signed_in? %>
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% end %>
    </nav>
  </header>